In [1]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3, 4, 5, 6], [8, 9, 10, 11, 12, 13]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [8]:
output = np.ones((7, 7))
output

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [9]:
a = np.array([1, 2, 3, 4, 5])
b = a
b[2] = 20
a

array([ 1,  2, 20,  4,  5])

In [10]:
a = np.array([1, 2, 3, 4, 5])
b = a.copy()
b[2] = 20
a

array([1, 2, 3, 4, 5])


filedata = np.genfromtxt('data.txt', delimiter=',')
output = np.any(filedata > 50)

In [11]:
a = np.array([[22., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 55., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 66., 1., 1.],
       [1., 1., 1., 1., 1., 11., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])
output = np.any(a > 50)
output

True